title: Heicode Docs
description: Heicode 产品文档
remote_theme: just-the-docs/just-the-docs

url: https://xmindlab-heicode.github.io

plugins:
  - jekyll-remote-theme

# 中文支持
lang: zh-CN

# 导航顺序
nav_sort: case_insensitive
